#!/usr/bin/python3

import argparse
from colorama import Fore, Style
import os
import random
import subprocess
import time

print(Fore.GREEN + Style.BRIGHT + '''
                     _ ___ ____        _  _   
 _ __ __ _ _ __   __| |_ _|  _ \__   _| || |  
| '__/ _` | '_ \ / _` || || |_) \ \ / / || |_ 
| | | (_| | | | | (_| || ||  __/ \ V /|__   _|
|_|  \__,_|_| |_|\__,_|___|_|     \_/    |_|  
''' + Style.RESET_ALL)
print(Fore.CYAN + Style.BRIGHT + "from mc3X" + Style.RESET_ALL)

z = 0
csnm = random.randint(1, 32)

parser = argparse.ArgumentParser(description="This script is for the local and Public IP", epilog="All settings will be reset at the end of this program")
parser.add_argument("-c", "--connect", type=str, default=None, help="Select public or local")
parser.add_argument("-m", "--mode", type=str, default=None, help="Select auto or manuel")
parser.add_argument("-n", "--nic", type=str, default=None, help="Select NIC (wlan0, eth0, etc.)")
parser.add_argument("-t", "--time", type=int, default=None, help="Enter time for script (mode=manual)")
args = parser.parse_args()



def change_mac(interface):
    subprocess.run(['sudo', 'ifconfig', interface, 'down'], check=True)
    subprocess.run(['sudo', 'macchanger', '-r', interface], check=True)
    subprocess.run(['sudo', 'ifconfig', interface, 'up'], check=True)

def check_and_change():
    ip = ".".join(map(str, (random.randint(0, 255) for _ in range(4))))
    response = os.system("ping -c 1 " + ip)
    #IP is up and can't by used for you
    if response == 0:
        while True:
            #New IP scan
            if response != 0:
                #When IP is free
                break
    #IP is down and can by used
    elif response != 0:
        global free_ip
        free_ip = ip


###
if os.getuid() != 0:
    exit(Fore.RED + Style.BRIGHT + "You need root!" + Style.RESET_ALL)
else:
    try:
        if args.connect == 'local':
            ii = input("Do you use your WiFi? [y/n]:")
            if ii == 'y' or 'Y':
                if args.mode == 'auto':
                    print(Fore.GREEN + Style.BRIGHT + "##Automatic Mode Started##" + Style.RESET_ALL)
                    print("")
                    while True:
                        z += 1
                        change_mac(args.nic)
                        check_and_change()
                        subprocess.run(['sudo', 'ifconfig', args.nic, free_ip, csnm], check=True)
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        print(Fore.GREEN + f"IP-Address of NIC {args.nic} successful changed to {free_ip}/{csnm}" + Style.RESET_ALL, end="\n")
                        time.sleep(120)
                if args.mode == 'manuel':
                    print(Fore.GREEN + Style.BRIGHT + "##Manual Mode Started##" + Style.RESET_ALL)
                    print("")
                    while True:
                        change_mac(args.nic)            
                        check_and_change()
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        print(Fore.GREEN + f"IP-Address of NIC {args.nic} successful changed to {free_ip}/{csnm}" + Style.RESET_ALL, end="\n")
                        time.sleep(args.time)
                        z += 1 
            elif ii == 'n' or 'no':
                if args.mode == 'auto':
                    print(Fore.GREEN + Style.BRIGHT + "##Automatic Mode Started##" + Style.RESET_ALL)
                    print("")
                    while True:
                        change_mac(args.nic)
                        check_and_change()
                        os.system(f"sudo ifconfig {args.nic} down")
                        subprocess.run(['sudo', 'ifconfig', args.nic, free_ip, csnm], check=True)
                        os.system(f"sudo ifconfig {args.nic} up")
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        print(Fore.GREEN + f"IP-Address of NIC {args.nic} successful changed to {free_ip}/{csnm}" + Style.RESET_ALL, end="\n")
                        time.sleep(120)
                        z += 1
                if args.mode == 'manuel':
                    print(Fore.GREEN + Style.BRIGHT + "##Manual Mode Started##" + Style.RESET_ALL)
                    print("")
                    while True:
                        change_mac(args.nic)
                        check_and_change()
                        os.system(f"sudo ifconfig {args.nic} down")
                        subprocess.run(['sudo', 'ifconfig', args.nic, free_ip, csnm], check=True)
                        os.system(f"sudo ifconfig {args.nic} up")
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        print(Fore.GREEN + f"IP-Address of NIC {args.nic} successful changed to {free_ip}/{csnm}" + Style.RESET_ALL, end="\n")
                        time.sleep(args.time)
                        z += 1 
            elif ii == None:
                exit()

        if args.connect == 'public':
            change_mac(args.nic)
            os.system('export socks_proxy="socks://127.0.0.1:9050"')
            if args.mode == 'auto':
                print(Fore.GREEN + Style.BRIGHT + "##Automatic Mode Selected##" + Style.RESET_ALL)
                os.system("sudo service tor stop")
                os.system("sudo service tor start")
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor reload")
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(30)
            elif args.mode == 'manuel':
                change_mac(args.nic)
                os.system('export socks_proxy="socks://127.0.0.1:9050"')
                print(Fore.GREEN + Style.BRIGHT + "##Manual Mode Selected##" + Style.RESET_ALL)
                os.system("sudo service tor stop")
                os.system("sudo service tor start")
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor restart")
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(args.time)

    except KeyboardInterrupt:
        if args.connect == 'public':
            os.system("export -n socks_proxy")
            os.system("sudo service tor stop")
            print("")
            exit(Fore.RED + Style.BRIGHT + "You stopped the script!" + Style.RESET_ALL)
        elif args.connect == 'local':
            subprocess.run(["sudo macchanger -p", args.nic], check=True)
            print("")
            exit(Fore.RED + Style.BRIGHT, "You stopped the script!" + Style.RESET_ALL)
        elif args.connect == 'local' and args.connect == 'public':
            os.system("export -n socks_proxy")
            os.system("sudo service tor stop")
            subprocess.run(["sudo macchanger -p", args.nic], check=True)
            print("")
            exit(Fore.RED + Style.BRIGHT, "You stopped the script!" + Style.RESET_ALL)
