#!/usr/bin/python3

import argparse
from colorama import Fore, Style
import os
import random
import subprocess
import time

print(Fore.GREEN + Style.BRIGHT + '''
                     _ ___ ____        _  _   
 _ __ __ _ _ __   __| |_ _|  _ \__   _| || |  
| '__/ _` | '_ \ / _` || || |_) \ \ / / || |_ 
| | | (_| | | | | (_| || ||  __/ \ V /|__   _|
|_|  \__,_|_| |_|\__,_|___|_|     \_/    |_|  
''' + Style.RESET_ALL)
print(Fore.CYAN + Style.BRIGHT + "from mc3X" + Style.RESET_ALL)

ip = ".".join(map(str, (random.randint(0, 255) for _ in range(4))))
z = 0
parser = argparse.ArgumentParser(description="This script is for the local and Public IP")
parser.add_argument("-c", "--connect", type=str, help="Select public or local")
parser.add_argument("-m", "--mode", type=str, help="Select auto or manual")
parser.add_argument("-i", "--iface", type=str, help="Enter 'wlan' or 'ethernet'")
parser.add_argument("-n", "--nic", type=str, help="Select NIC (wlan0, eth0, etc.)")
parser.add_argument("-mc", "--mac", type=str, help="This is for change your mac-address on NIC (default deaktivated, to activate type yes and use --nic)")
parser.add_argument("-t", "--time", type=int, help="Enter time for script")
args = parser.parse_args()

def change_ip_address_eth(interface, new_ip):
    subprocess.run(['sudo', 'ifconfig', interface, 'down'], check=True)
    subprocess.run(['sudo', 'ifconfig', interface, new_ip], check=True)
    subprocess.run(['sudo', 'ifconfig', interface, 'up'], check=True)
    print(f"IP-Address of NIC {interface} successful changed to {new_ip}")

def change_ip_address_wlan(interface, new_ip):
    subprocess.run(['sudo', 'ifconfig', interface, new_ip], check=True)
    print(f"IP-Address of NIC {interface} successful changed to {new_ip}")

def change_mac(interface):
    subprocess.run(['sudo', 'ifconfig', interface, 'down'], check=True)
    subprocess.run(['sudo', 'macchanger', '-r', interface], check=True)
    subprocess.run(['sudo', 'ifconfig', interface, 'up'], check=True)

def check_ping_eth():
    ip = ".".join(map(str, (random.randint(0, 255) for _ in range(4))))
    response = os.system("ping -c 1 " + ip)
    #IP is up and can't by used
    if response == 0:
        while True:
            #New scan
            if response != 0:
                #IP is free
                break
    #IP is down and can by used
    elif response != 0:
        change_ip_address_eth(args.nic, ip)

def check_ping_wlan():
    ip = ".".join(map(str, (random.randint(0, 255) for _ in range(4))))
    response = os.system("ping -c 1 " + ip)
    #IP is up and can't by used
    if response == 0:
        while True:
            #New scan
            if response != 0:
                #IP is free
                break
    #IP is down and can by used
    elif response != 0:
        change_ip_address_wlan(args.nic, ip)

if os.getuid() != 0:
    exit(Fore.RED + Style.BRIGHT + "You need root!" + Style.RESET_ALL)

try:
    if args.connect == 'public':
        if args.mode == 'auto':
            print(Fore.GREEN + Style.BRIGHT + "##Automatic Mode Selected##" + Style.RESET_ALL)
            os.system("sudo service tor stop")
            os.system("sudo service tor start")
            if args.mac == 'yes':
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor reload")
                    change_mac(args.nic)
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(30)
            else:
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor reload")
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(30)
        elif args.mode == 'manual':
            print(Fore.GREEN + Style.BRIGHT + "##Manual Mode Selected##" + Style.RESET_ALL)
            os.system("sudo service tor stop")
            os.system("sudo service tor start")
            if args.mac == 'yes':
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor restart")
                    change_mac(args.nic)
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(args.time)
            else:
                print("")
                print(Fore.BLUE + Style.BRIGHT + "Started at: ", time.ctime())
                while True:
                    z += 1
                    os.system("sudo service tor restart")
                    print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", Fore.RED + "  Time of Last change: ", time.ctime(), "|  Time to restart: ", args.time, end="\r" + Style.RESET_ALL)
                    time.sleep(args.time)

    elif args.connect == 'local':
        if args.mode == 'auto':
            print(Fore.GREEN + Style.BRIGHT + "##Automatic Mode Started##" + Style.RESET_ALL)
            if args.iface == 'ethernet':
                if args.mac == 'yes':
                    print("")
                    while True:
                        z += 1
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_eth()
                        change_mac(args.nic)
                        time.sleep(120)
                else:
                    print("")
                    while True:
                        z += 1
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_eth()
                        time.sleep(120)
            elif args.iface == 'wlan':
                if args.mac == 'yes':
                    print("")
                    while True:
                        z += 1
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_wlan()
                        change_mac(args.nic)
                        time.sleep(120)
                else:
                    print("")
                    while True:
                        z += 1
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_wlan
                        time.sleep(120)
        elif args.mode == 'manual':
            print(Fore.GREEN + Style.BRIGHT + "##Manual Mode Started##" + Style.RESET_ALL)
            if args.iface == 'ethernet':
                if args.mac == 'yes':
                    print("")
                    while True:
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_eth()
                        change_mac(args.nic)
                        time.sleep(args.time)
                        z += 1
                else:
                    print("")
                    while True:
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_eth()
                        time.sleep(args.time)
                        z += 1
            elif args.iface == 'wlan':
                if args.mac == 'yes':
                    print("")
                    while True:
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_wlan()
                        change_mac(args.nic)
                        z += 1
                        time.sleep(args.time)
                else:
                    print("")
                    while True:
                        print(Fore.GREEN + Style.BRIGHT + f"##RESET {z} COMPLETE##", end="\r" + Style.RESET_ALL)
                        check_ping_wlan()
                        z += 1
                        time.sleep(args.time)
except KeyboardInterrupt:
    try:
        os.system("sudo service tor stop")
        subprocess.run(["sudo macchanger -p", args.nic], check=True)
        print("")
        print(Fore.RED + Style.BRIGHT + "You stopped the script!" + Style.RESET_ALL)
        print(Fore.RED + "All changes are resetet" + Style.RESET_ALL)
        exit()
    except:
        os.system("sudo service tor stop")
        print(Fore.RED + Style.BRIGHT + "You stopped the script!" + Style.RESET_ALL)
        print(Fore.RED + "All changes are resetet" + Style.RESET_ALL)
        exit()